package com.JLMSite.service;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.JLMSite.model.Visitor;
import com.JLMSite.repository.VisitorRepository;

@Service // This means that this class is a service
public class VisitorService {

	@Autowired 
	// to get the bean (VisitorRepository) which is auto-generated by Spring
	//	We will use it to handle the data
	VisitorRepository visitorRepository;
	
	//get a list of visitors
	public List<Visitor> getAllVisitors()
	{
		//		find all visitors data, then return it
		return visitorRepository.findAll(); //<== a JPA method
	}
	
	//save a visitor
	public void saveVisitor(Visitor vis)
	{
		// Save visitor to the database, another JPA method
		visitorRepository.save(vis);
	}
	
	//get a visitor by ID
	public Visitor getVisitorById(Long id)
	{
		//Gotta put our objects in an Optional object in order to be compatible with JPA repo methods like findById.
		//Optional objects help prevent null pointer exceptions
		Optional<Visitor> vis = visitorRepository.findById(id);
		
		if (!vis.isPresent())
		{
			throw new RuntimeException("NoOne by that Id");
		}
		return vis.get();//Using get() returns the value (in this case the visitor object) of the Optional object
	}
	
	//delete a visitor by Id
	public String deleteVisitorById(Long id)
	{
		Optional<Visitor> vis = visitorRepository.findById(id);
		
		if (!vis.isPresent())
		{
			throw new RuntimeException("NoOne by that Id");
		}
		
		visitorRepository.deleteById(id);
		return "Deleted: " + vis.get().getFirstName() + " " + vis.get().getLastName();
	}
	
}
